@echo off
setlocal

cd /d "%~dp0bot"

echo.
echo ============================================================
echo  QTB clear simulated paper trades
echo ============================================================
echo.
echo This deletes only records generated by paper_simulated_v1.
echo It does not target future real DEMO records.
echo.

python tools\clear_paper_trades.py
echo.
set /p CONFIRM=Type DELETE to remove the paper/simulated records: 
if /i not "%CONFIRM%"=="DELETE" goto cancelled

python tools\clear_paper_trades.py --yes
if errorlevel 1 goto error

echo.
echo Exporting remaining trades after cleanup...
python tools\export_trades.py
if errorlevel 1 goto error

echo.
echo Done.
echo.
pause
exit /b 0

:cancelled
echo.
echo Cancelled. No records were deleted.
echo.
pause
exit /b 0

:error
echo.
echo Cleanup failed. Copy the output above and send it for review.
echo.
pause
exit /b 1
